### ISSUE TITLE
Image path needs to be updated

### ISSUE THREAD

**Issue by kristofj-umd** [johnzmyslony/Final_Project#6]
https://github.com/johnzmyslony/Final_Project/blob/d3c2819594742246b1a3dcc99780941fa36fb5e7/index.html#L278

It looks like the bus route images as you have them saved are like `.....JPG` whereas in the code you are referencing them as `....jpg`. [See here](https://github.com/johnzmyslony/Final_Project/blob/master/route_schedule_pdfs/route_7_toDT_sunday.JPG) 
This breaks the images on the side panel.

**Comment by johnzmyslony** [comment]
I fixed the issue. I made all .jpg into .JPG except for busroute21.jpg which remains lower case. The file paths did not update right away on the GitHub pages link but after a few minutes they worked. Let me know if it still doesn't work for you.
